### ISSUE TITLE
FullCalendarBehaviorImplementation not defined after vulcanization

### ISSUE THREAD

**Issue by abcirta** [sorin-davidoi/fullcalendar-calendar#10]
Hello,

Thank you for this useful component!

I've encountred an issue after vulcanization of my application (no issues before vulcanization). The page won't load and the console shows an unexpected error: FullCalendarBehaviorImplementation is not defined.

I was able to fix that by modifying:
full-calendar-behavior: 
- line 9: FullCalendarBehaviorImplementation => var FullCalendarBehaviorImplementation
- line 465: FullCalendarBehavior => Polymer.FullCalendarBehavior

fullcalendar-calendar and fullcalendar-calendar-no-deps:
- Set behaviors: behaviors: [ Polymer.FullCalendarBehavior ]

With those modifications, the component and my app are working before and after vulcanization.

Feel free to contact me if you need further information.

Best regards,
Arslan

**Comment by sorin-davidoi** [comment]
Hi,

Thanks for taking the time to report this. I am unable to replicate your issue, but I took a closer look at the behavior and fixed an issue that might have caused the error. I have committed to `master`, but did not create a release yet.

Can you give this one a go and let me know if it fixes your problem?

``` bash
$ bower install https://github.com/sorin-davidoi/fullcalendar-calendar.git#master
```

**Comment by abcirta** [comment]
Hello,

Thanks for the quick feedback.
The "master" version is indeed working after the vulcanization process, good work!

Cheers,
Arslan

**Comment by sorin-davidoi** [comment]
Alright, will make a release then.
