### ISSUE TITLE
Dynamically set a calendar's option after initialization

### ISSUE THREAD

**Issue by andrewspy** [sorin-davidoi/fullcalendar-calendar#13]
Is there a equivalent custom element's method to dynamically set a calendar's option using the equivalent native fullcalendar's code below:-

```js
$('#calendar').fullCalendar('option', 'aspectRatio', 1.8);
```

**Comment by sorin-davidoi** [comment]
The calendar element is exposed as [`_calendar`](https://github.com/sorin-davidoi/fullcalendar-calendar/blob/master/behaviors/full-calendar-behavior.html#L231), so this should work:

```js
this.$.myCalendar._calendar.fullCalendar('option', 'aspectRatio', 1.8)
```

**Comment by andrewspy** [comment]
@sorin-davidoi Yes, it does work. Thanks for the pointer.
