### ISSUE TITLE
In Safar & Firefox the theme doesn't get applied

### ISSUE THREAD

**Issue by JaySunSyn** [sorin-davidoi/fullcalendar-calendar#2]
Thanks again for this element!!

The css seems not to get applied.
![bildschirmfoto 2016-06-16 um 12 26 42](https://cloud.githubusercontent.com/assets/5872432/16105507/a6562d98-33bd-11e6-877f-933999b3be4e.png)

**Comment by sorin-davidoi** [comment]
Fixed in [`v0.2.2`](https://github.com/sorin-davidoi/fullcalendar-calendar/releases/tag/v0.2.2).

**Comment by JaySunSyn** [comment]
Awesome @sorin-davidoi! Many thanks!
